### ISSUE TITLE
Feature request: Target .Net 4.6.1 / .Net Core

### ISSUE THREAD

**Issue by Hecatron** [umairsyed613/Serilog.Sinks.WinForms#1]
Hi,
Is there any chance you could add Nuget targets for .Net 4.6.1 (this seems to be the lowest version it will support), and or .Net Core now that it has winforms support?

**Comment by umairsyed613** [comment]
Sure, I ll look into it :)

**Comment by PatrickFranken** [comment]
Would love to see at least 4.7.2 support, thanks for looking into it!

**Comment by umairsyed613** [comment]
I have downgraded the library to net46 it will work now i guess :) give it a star if you find this worthy of use
https://www.nuget.org/packages/Serilog.Sinks.WinForms/2.2.2
