### ISSUE TITLE
Configuring logs to specific outputs

### ISSUE THREAD

**Issue by muratcanoguzhan** [umairsyed613/Serilog.Sinks.WinForms#10]
Is there a way to have two RichTextBoxLogControl and fill them with different outputs because context like special class `MyClass` doesn't work;

| RichTextBoxLogControl 1  | RichTextBoxLogControl 2 |
| ------------- | ------------- |
| Log for 1  | Log for 2 |
| Another Log for 1  | Another Log for 2  |

**Comment by umairsyed613** [comment]
Did you try ForContext property on the richtextbox?

**Comment by umairsyed613** [comment]
ForContext should be like namespace.classname

**Comment by muratcanoguzhan** [comment]
Yes I tried ForContext property and I also opened the Enrich and it didn't work for a particular class but when I downloaded your project it worked for your subform. It would be good to use it for a particular class.

**Comment by umairsyed613** [comment]
It should be working through nuget package as well.. i will check why its not working with published package

**Comment by umairsyed613** [comment]
@muratcanoguzhan  please try this version
https://www.nuget.org/packages/Serilog.Sinks.WinForms/2.4.3
