### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by Talsiter** [umairsyed613/Serilog.Sinks.WinForms#2]
First off. I absolutely love this Sink!!!! Thank you!!!

Is there a way to add an output template option for WriteToSimpleTextBox?
EXAMPLE:
        .WriteToSimpleTextBox(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"))

BTY, Did I tell you THANK YOU!! and that I LOVE this Sink!!!!!!

**Comment by umairsyed613** [comment]
Yes its possible if you donot use the extension method and create your own object and configure it with log configuration

**Comment by umairsyed613** [comment]
I will try to make a example code. And add it to docs

**Comment by Talsiter** [comment]
> Yes its possible if you do not use the extension method and create your own object and configure it with log configuration.

Yea, I kinda figured that I could hard code it. in the extension (that is actually what I ended up doing). With that said, I figured I was missing how to do it with the sink.

Regardless, I LOVE IT!

Thank you.

**Comment by umairsyed613** [comment]
@Talsiter V2.2.3 is added where you can put your own Formatting settings when configuring the logger. read the docs again
https://www.nuget.org/packages/Serilog.Sinks.WinForms/2.2.3
