### ISSUE TITLE
Control does not support transparent background colors.

### ISSUE THREAD

**Issue by ghost** [umairsyed613/Serilog.Sinks.WinForms#4]
**Describe the bug**
When dragging and dropping a SimpleLogTextBox or a JsonLogTextBox control from the Toolbox onto my Form's Designer View, Visual Studio displays an error in a popup saying, "Control does not support transparent background colors." The control is not added to my Form.

**To Reproduce**
1. Go to 'Toolbox'
2. Drag a SimpleLogTextBox control onto your Form.
3. A popup is displayed with the error, "Control does not support transparent background colors."

**Expected behavior**
The Control is expected to appear on my Form's Designer View, but doesn't.

**Screenshots**
![controlerror](https://user-images.githubusercontent.com/66349788/108263155-1d0b3580-7123-11eb-9549-c82c2ccbe21c.png)

**Desktop (please complete the following information):**
 - Windows 8.1
 - Visual Studio 2017 Community
 - My Project 4.6.1 Framework
 - NuGet packages
 - Serilog
 - Serilog.Sinks.ColoredConsole
 - Serilog.Sinks.Console
 - Serilog.Sinks.File
 - Serilog.Sinks.WinForms

**Additional Info**
I have tried different projects and have tried adding the following line to my Form, with no luck:
 this.SetStyle(ControlStyles.SupportsTransparentBackColor, true);

**Comment by umairsyed613** [comment]
I will try to fix that tomorrow

**Comment by umairsyed613** [comment]
@TommyS7000  new version release, v2.2.4 you will find the new TransparentSimpleLogTextBox in toolbox. and sample application is also added

**Comment by ghost** [comment]
Hi. Thanks for your help and for the fast response.

Unfortunately, I am confused about your response. I took a look at the new TransparentSimpleLogTextBox, and I was able to drag and drop it onto my default WinForms project in Visual Studio. However, it has some serious problems with usability and seems very undesirable. I can discuss those issues if you are interested. However, this response is to figure out how to use the previously provided controls. I am guessing, that since you did not fix the other controls, that they are in fact able to be dragged and dropped onto some Windows Forms. Can you explain this issue and why it wasn't fixed and how I can hack my Visual Studio Environment and/or how to hack the default Windows Form provided to me by Visual Studio, in order to be able to drag and drop your controls onto my default Windows Form?

In addition, I will open a feature request for a RichTextBoxLog control that is draggable onto my default Windows Form, has the same usability, and looks like a default RichTextBox. This is the control that I was searching for, when I came across your project. None of the other controls really fit my needs. I hope you will implement it.

Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by umairsyed613** [comment]
can you write all the issues in points?
you can still fetch all the controls on your windows form where you are settings the backcolor to transparent but you will not be able to run the application it will show you the error that you are previously getting. and if you use the new transparentlog it will be working. but what are the issues you are facing with the new control?

**Comment by umairsyed613** [comment]
you can also make your own textbox and get the logs into that.
see this sample project
https://github.com/umairsyed613/Serilog.Sinks.WinForms/tree/master/src/Sample/CustomSimpleTextLog


and I have also released a new version with richtextbox control.

**Comment by umairsyed613** [comment]
give it a start if your problem solves and you find this project worth having a star :)

**Comment by ghost** [comment]
Hi. Thanks again for a response, but I am still very confused about your responses.

"can you write all the issues in points?"
Yes, but first I would like to have the first issue addressed before moving on to all the other issues. I will attempt to ask for help with the first issue a 3rd time.

"you can still fetch all the controls on your windows form"
I have no idea what this means and I can't find anything whatsoever in Visual Studio that could possibly have anything to do with "fetching."

"your windows form where you are settings the backcolor to transparent"
I have no idea where you got his information, but it didn't come from me. I am not setting ANY color of ANYTHING whatsoever on ANY form in Visual Studio. As I clearly stated, I created a default Windows Forms App (.Net Framework) C# application and added your NuGet package. The controls that I asked about are not able to be dragged and dropped onto the form. Everything else in Visual Studio and everything else in all of my projects is all working correctly without any errors.

**Comment by ghost** [comment]
I tried the RichTextBoxLogControl and it has the same problems as the TransparentSimpleLogTextBox and is completely unusable. Having a log with invisible text is unprofessional and doesn't work for me. Additionally, this new control does NOT have the same LOOK and feel as a default RichTextBox.

Thanks for your responses, but I simply don't have the time to keep asking and answering the same questions over and over. I will move on to something else.

Thanks and good luck.
