### ISSUE TITLE
I dont see the serilog control in toolbox

### ISSUE THREAD

**Issue by alejo9010** [umairsyed613/Serilog.Sinks.WinForms#7]
hello. i dont see the controls in the toolbox for serilog richbox and etc. how can i enable them ?

**Comment by Talsiter** [comment]
@alejo9010, assuming that you are using Visual Studio 2019:
After downloading the code, build and run the sample program. Once the program is built the controls will appear in your toolbox.

If you have any additional question, please let me know.

I am also assuming that once the program is built, you know how to add the control to a new program. If not, please let me know.

Good luck!

**Comment by alejo9010** [comment]
hi thanks for answering, but i still cant see the control, i cant even see the control in you sample code, i see the controls in the form, but not in the toolbox, also i tried using the other method (WindFormsSink.SimpleTextBoxSink.OnLogReceived += SimpleTextBoxSinkOnOnLogReceived;) but, its giving me errors when triying to log inside tasks, or other threads.

**Comment by Talsiter** [comment]
@alejo9010 , sorry I didn't explain myself better. I created a quick video to show you exactly what I did. You can find the video at: https://youtu.be/ycSm7W0Z9Tc 

Please let me know if this helps you.

**Comment by umairsyed613** [comment]
If you are using a package from nuget just build your project and you should be able to see them in toolbox  if not you can manually browser the dll and add controls to your toolbox.
