### ISSUE TITLE
Release for .net 5 framework 

### ISSUE THREAD

**Issue by zombiehunter1** [umairsyed613/Serilog.Sinks.WinForms#8]
Hi,  is it possible to release this for .net 5?

**Comment by umairsyed613** [comment]
Yes soon

**Comment by umairsyed613** [comment]
@zombiehunter1  here is the package you can download. dnt forget to give it a star :)
https://www.nuget.org/packages/Serilog.Sinks.WinForms.Core/1.0.0

**Comment by muratcanoguzhan** [comment]
> @zombiehunter1 here is the package you can download. dnt forget to give it a star :) https://www.nuget.org/packages/Serilog.Sinks.WinForms.Core/1.0.0

It doesn't work.

**Comment by umairsyed613** [comment]
https://github.com/umairsyed613/Serilog.Sinks.WinForms/tree/main/src/Sample/TestApplicationNet6

check this sample app

**Comment by muratcanoguzhan** [comment]
> https://github.com/umairsyed613/Serilog.Sinks.WinForms/tree/main/src/Sample/TestApplicationNet6
> 
> check this sample app

Sorry, when I said it doesn't work the problem is about when I try to install it via nuget package it gives server error. It is like nobody can not download this package.

**Comment by umairsyed613** [comment]
@muratcanoguzhan  i have created a new package and published it, i will test it and will update you

**Comment by umairsyed613** [comment]
Download this https://www.nuget.org/packages/Serilog.Sinks.WinForms.Core/1.0.1
hopefully it will work :)

**Comment by muratcanoguzhan** [comment]
> Download this https://www.nuget.org/packages/Serilog.Sinks.WinForms.Core/1.0.1 hopefully it will work :)

After downloading the 1.0.2 version it works. Thank you.
